78040 - Get ipo details
equinor/procosys-invitation-for-punch-out-api pull request #23
Opened 2020-10-27 15:24 UTC by llykkelarsen

DevOps#78040

Get invitation endpoint
Persons which become participants through a functional role (use personal email: yes) are now saved with their respective functional role codes in the db. This is to keep track of which persons are under a functional role and which are not.

2020-10-28 08:17 UTC, bratli approved these changes

2020-10-28 08:17 UTC, bratli commented on src/tests/Equinor.ProCoSys.IPO.Query.Tests/GetInvitationById/GetInvitationByIdQueryHandlerTests.cs
> +                    Organization.Contractor,
This doesnt affect your test, but in reality we should never have a participant with sortkey=1, with organization.Contractor. If sortkey=1 the organization is ConstructionCompany

2020-10-28 08:51 UTC, bratli requested changes
We need to have db id on participants, mcpkgs and commpkgs, and invitation

2020-11-04 11:56 UTC, llykkelarsen commented
@bratli Ready for review

2020-11-04 12:57 UTC, bratli requested changes

2020-11-04 12:57 UTC, bratli commented on src/Equinor.ProCoSys.IPO.Query/GetInvitationById/FunctionalRoleDto.cs
> +        public FunctionalRoleDto(
rowVersion?

2020-11-04 12:57 UTC, bratli commented on src/Equinor.ProCoSys.IPO.Query/GetInvitationById/ParticipantDto.cs
> +        public string RowVersion { get; }
I think rowVersion needs to be on ExternalEmailDto, FunctionalRoleDto, and PersonDto instead of on ParticipantDto

2020-11-04 12:57 UTC, bratli commented on src/Equinor.ProCoSys.IPO.Query/GetInvitationById/GetInvitationByIdQueryHandler.cs
> +                        null, ConvertToFunctionalRoleDto(participant, personsInFunctionalRole), participant.RowVersion.ConvertToString()));
RowVersion not on participantDto, but on ExternalEmailDto, FunctionalRoleDto, and PersonDto

2020-11-05 07:59 UTC, bratli approved these changes

2020-11-05 08:01 UTC, merged