Migrations for new Guid property on Project, McPkg and CommPkg
equinor/procosys-invitation-for-punch-out-api pull request #286
Opened 2023-10-30 13:47 UTC by terjewoldseth

Updatet constructor and test for Project

2023-11-14 12:16 UTC, arildbjerkenes approved these changes

2023-11-15 05:59 UTC, janid1967 commented on src/Equinor.ProCoSys.IPO.Command/CommPkgCommands/FillPcsGuids/FillCommPkgPcsGuidsCommand.cs
> +namespace Equinor.ProCoSys.IPO.Command.CommPkgCommands.FillCommPkgPcsGuids
ns mismatch folder

2023-11-15 05:59 UTC, janid1967 commented on src/Equinor.ProCoSys.IPO.Command/CommPkgCommands/FillPcsGuids/FillCommPkgPcsGuidsCommandHandler.cs
> +namespace Equinor.ProCoSys.IPO.Command.CommPkgCommands.FillCommPkgPcsGuids
ns mismatch folder

2023-11-15 06:00 UTC, janid1967 commented on src/Equinor.ProCoSys.IPO.Command/McPkgCommands/FillPcsGuids/FillMcPkgPcsGuidsCommandHandler.cs
> +namespace Equinor.ProCoSys.IPO.Command.McPkgCommands.FillMcPkgPcsGuids
ns mismatch folder

2023-11-15 06:00 UTC, janid1967 commented on src/Equinor.ProCoSys.IPO.Command/McPkgCommands/FillPcsGuids/FillMcPkgPcsGuidsCommand.cs
> +namespace Equinor.ProCoSys.IPO.Command.McPkgCommands.FillMcPkgPcsGuids
ns mismatch folder

2023-11-15 06:01 UTC, janid1967 commented on src/Equinor.ProCoSys.IPO.Command/McPkgCommands/FillPcsGuids/FillMcPkgPcsGuidsCommandHandler.cs
> +using global::Equinor.ProCoSys.IPO.ForeignApi.MainApi.Project;
remove unused usings

2023-11-15 06:02 UTC, janid1967 commented on src/Equinor.ProCoSys.IPO.Command/McPkgCommands/FillPcsGuids/FillMcPkgPcsGuidsCommandHandler.cs
> +        private readonly ICommPkgApiService _commPkgApiService;
remove, not used

2023-11-15 06:03 UTC, janid1967 commented on src/Equinor.ProCoSys.IPO.Command/McPkgCommands/FillPcsGuids/FillMcPkgPcsGuidsCommandHandler.cs
> +          if (request.SaveChanges && count > 0)
indent

2023-11-15 06:03 UTC, janid1967 commented on src/Equinor.ProCoSys.IPO.Command/ProjectCommands/FillPcsGuids/FillProjectPcsGuidsCommandHandler.cs
> +using System.Linq;
remove unused usings

2023-11-15 06:04 UTC, janid1967 commented on src/Equinor.ProCoSys.IPO.Command/ProjectCommands/FillPcsGuids/FillProjectPcsGuidsCommand.cs
> +namespace Equinor.ProCoSys.IPO.Command.ProjectCommands.FillProjectPcsGuids
ns mismatch folder

2023-11-15 06:04 UTC, janid1967 commented on src/Equinor.ProCoSys.IPO.Command/ProjectCommands/FillPcsGuids/FillProjectPcsGuidsCommandHandler.cs
> +namespace Equinor.ProCoSys.IPO.Command.ProjectCommands.FillProjectPcsGuids
ns mismatch folder

2023-11-15 06:04 UTC, janid1967 commented on src/Equinor.ProCoSys.IPO.Command/ProjectCommands/FillPcsGuids/FillProjectPcsGuidsCommandHandler.cs
> +          if (request.SaveChanges && count > 0)
indent

2023-11-15 06:08 UTC, janid1967 commented on src/Equinor.ProCoSys.IPO.Domain/AggregateModels/InvitationAggregate/CommPkg.cs
> +        public Guid Guid { get; set; } = Guid.Empty;
remove init  Guid.Empty;
Add a Todo // make this private after FillGuids is completed

2023-11-15 06:10 UTC, janid1967 commented on src/Equinor.ProCoSys.IPO.Domain/AggregateModels/ProjectAggregate/Project.cs
> +        public Guid Guid { get; set; } = Guid.Empty;
remove init Guid.Empty;
Add a Todo // make Guid private after FillGuids is completed

2023-11-15 06:12 UTC, janid1967 commented on src/Equinor.ProCoSys.IPO.Domain/AggregateModels/InvitationAggregate/CommPkg.cs
Remove property SystemSubString. Not in use

2023-11-15 06:12 UTC, janid1967 commented on src/Equinor.ProCoSys.IPO.Domain/AggregateModels/InvitationAggregate/McPkg.cs
Remove property SystemSubString. Not in use

2023-11-15 06:13 UTC, janid1967 commented on src/Equinor.ProCoSys.IPO.Domain/AggregateModels/InvitationAggregate/McPkg.cs
> +        public Guid Guid { get; set; } = Guid.Empty;
remove init Guid.Empty;
Add a Todo // make Guid private after FillGuids is completed

2023-11-15 06:14 UTC, janid1967 commented on src/Equinor.ProCoSys.IPO.ForeignApi/MainApi/McPkg/IMcPkgApiService.cs
> +        Task<ProCoSysMcPkg> GetMcPkgByIdAsync(string plant, long mcPkgNo);
mcPkgId

2023-11-15 06:14 UTC, janid1967 commented on src/Equinor.ProCoSys.IPO.ForeignApi/MainApi/McPkg/MainApiMcPkgService.cs
> +            long mcPkgNo)
mcPkgId

2023-11-15 06:16 UTC, janid1967 commented on src/tests/Equinor.ProCoSys.IPO.Command.Tests/InvitationCommands/AcceptPunchOut/AcceptPunchOutCommandHandlerTests.cs
> +        private static readonly Guid _project1uid = new Guid("11111111-2222-2222-2222-333333333341");
_project1Guid

2023-11-15 06:21 UTC, janid1967 commented on src/tests/Equinor.ProCoSys.IPO.Domain.Tests/AggregateModels/InvitationAggregate/CommPkgTests.cs
> +        private readonly Guid CommPkgGuid = Guid.Empty;
make CommPkgGuid other than empty and Assert it is set in Constructor_ShouldSetProperties()

2023-11-15 06:24 UTC, janid1967 commented on src/tests/Equinor.ProCoSys.IPO.Domain.Tests/AggregateModels/InvitationAggregate/McPkgTests.cs
> +            _dut = new McPkg(TestPlant, _project, CommPkgNo, McPkgNo, Description, System, Guid.Empty);
Add a private readonly McPkgGuid other than empty to set here, and Assert it is set in Constructor_ShouldSetProperties()

2023-11-15 06:29 UTC, janid1967 commented
Add a testclass for the Project domain class in src/tests/Equinor.ProCoSys.IPO.Domain.Tests/AggregateModels/InvitationAggregate/ Use McPkgTests.cs as template, just Setup and Constructor_ShouldSetProperties() needed

2023-11-15 06:33 UTC, janid1967 requested changes
See comments

2023-11-15 09:59 UTC, janid1967 approved these changes
Approved w minor improvements in CommPkgTests.cs and McPkgTests.cs

2023-11-28 07:34 UTC, merged